name: Enviar tarefas do dia para o Telegram

on:
  schedule:
    - cron: '30 22 * * *'  # 19:30 BRT = 22:30 UTC
    - cron: '30 23 * * *'  # 20:30 BRT = 23:30 UTC
  workflow_dispatch:

jobs:
  enviar_mensagem:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests pytz

      - name: Executar script
        env:
          RUNRUN_APP_KEY: ${{ secrets.RUNRUN_APP_KEY }}
          RUNRUN_USER_TOKEN: ${{ secrets.RUNRUN_USER_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_CHAT_ID_SECUNDARIO: ${{ secrets.TELEGRAM_CHAT_ID_SECUNDARIO }}
        run: python runrun_telegram_report.py
