name: Enviar tarefas do dia para o Telegram

on:
  schedule:
    # Roda todo dia às 16h15 BRT (19h15 UTC)
    - cron: '15 19 * * *'
    # Roda todo dia às 19h00 BRT (22h00 UTC)
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  enviar_mensagem:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install requests pytz

      - name: Executar script
        env:
          RUNRUN_APP_KEY: ${{ secrets.RUNRUN_APP_KEY }}
          RUNRUN_USER_TOKEN: ${{ secrets.RUNRUN_USER_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python runrun_telegram_report.py
