name: Testar campo responsável Runrun.it

on:
  workflow_dispatch:  # permite rodar manualmente pelo GitHub

jobs:
  testar_responsavel:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar requests
        run: pip install requests

      - name: Rodar script para imprimir a primeira tarefa
        env:
          RUNRUN_APP_KEY: ${{ secrets.RUNRUN_APP_KEY }}
          RUNRUN_USER_TOKEN: ${{ secrets.RUNRUN_USER_TOKEN }}
        run: python runrun_telegram_report.py
